---
# tasks file for ansible-role-password-security/

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Install Password Quality PAM library package"
  ansible.builtin.package:
    name: "{{ cracklib_package }}"
    state: present

- name: "Enforce Password Quality in PAM"
  block:
    - name: "Change password cracklib library to required in password_auth"
      community.general.pamd:
        name: "{{ password_auth }}"
        type: password
        control: requisite
        module_path: pam_pwquality.so
        new_control: required
        backup: yes
    - name: "Change password cracklib library to required in system_auth (RedHat)"
      community.general.pamd:
        name: "{{ system_auth }}"
        type: password
        control: requisite
        module_path: pam_pwquality.so
        new_control: required
        backup: yes
      when: ansible_os_family == 'RedHat'

- name: "Enable Password Warning in PAM"
  block:
    - name: "Add password pam_warn.so to password-auth"
      community.general.pamd:
        name: "{{ password_auth }}"
        type: password
        control: required
        module_path: pam_deny.so
        new_type: password
        new_control: required
        new_module_path: pam_warn.so
        state: after
        backup: yes
    - name: "Add password pam_warn.so to system_auth (RedHat)"
      community.general.pamd:
        name: "{{ system_auth }}"
        type: password
        control: required
        module_path: pam_deny.so
        new_type: password
        new_control: required
        new_module_path: pam_warn.so
        state: after
        backup: yes
      when: ansible_os_family == 'RedHat'

- name: "Restart SSH Daemon"
  ansible.builtin.service:
    name: "{{ ssh_daemon }}"
    state: restarted